defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: alyssa
  password: 
  host: localhost

development:
  <<: *defaults
  database: facesofmadison_development

test:
  <<: *defaults
  database: facesofmadison_test
